version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: prismerp-postgres
    environment:
      POSTGRES_DB: prismerp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - prismerp_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: prismerp-redis
    ports:
      - "6379:6379"
    volumes:
      - prismerp_redis_data:/data

volumes:
  prismerp_postgres_data:
  prismerp_redis_data: